dist: xenial
sudo: required
language: java
jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm

before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx1536m"
    - THEME_VERSION=0.3.1

branches:
  only:
    - master
    - develop

stages:
  - name: Build
  - name: Release

jobs:
  include:
    - stage: "Build"
      name: "Build from develop branch"
      if: (branch = develop) AND type != pull_request
      before_script:
        - travis_fold start build_keycloak_server
      script:
        - cd server
        - make build_keycloak
      after_script:
        - travis_fold end build_keycloak_server
    - name: "Build from distribution zip"
      if: (branch = master) AND type != pull_request
      script:
        - cd server
        - make download_keycloak
    - name: "Build and Push images"
      script:
        - cd server
        - docker login quay.io -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}
        - make build_image push_private cleanup
    - stage: release
      name: "Release keycloak-containers in GitHub"
      if: (branch = master) AND type != pull_request AND commit_message !~ /\[no-release\]/
      script:
        - git config user.email "${GIT_EMAIL}"
        - git config user.name "${GIT_USERNAME}"
        - cd server && ./release.sh
